"""Versioned, bilingual demo curriculum. This is not an official MAShTI question bank."""

import uuid

from app.models.entities import Question, Skill, Subject

NAMESPACE = uuid.UUID("82f8e16d-66fc-4e28-a3de-4efb193bfb93")

SUBJECTS = [
    ("albanian", "Gjuhë shqipe", "Albanian", True),
    ("mathematics", "Matematikë", "Mathematics", True),
    ("english", "Gjuhë angleze", "English", True),
    ("history", "Histori", "History", False),
    ("biology", "Biologji", "Biology", False),
    ("informatics", "Informatikë", "Informatics", False),
]

SKILLS = [
    (
        "alb_reading",
        "albanian",
        "Kuptimi i tekstit",
        "Reading comprehension",
        "Kërko idenë që mbështetet drejtpërdrejt nga fjalia.",
        "Look for the idea directly supported by the sentence.",
    ),
    (
        "alb_grammar",
        "albanian",
        "Gramatikë",
        "Grammar",
        "Kontrollo rolin e secilës fjalë në fjali.",
        "Check the role of each word in the sentence.",
    ),
    (
        "alb_literature",
        "albanian",
        "Letërsi",
        "Literature",
        "Kujto tiparin kryesor të termit letrar.",
        "Recall the defining feature of the literary term.",
    ),
    (
        "math_algebra",
        "mathematics",
        "Algjebër",
        "Algebra",
        "Izolo të panjohurën duke kryer të njëjtin veprim në të dy anët.",
        "Isolate the unknown by applying the same operation to both sides.",
    ),
    (
        "math_geometry",
        "mathematics",
        "Gjeometri",
        "Geometry",
        "Vizato figurën dhe zgjidh formulën që përdor të dhënat.",
        "Sketch the figure and choose the formula that uses the given values.",
    ),
    (
        "math_data",
        "mathematics",
        "Të dhëna dhe probabilitet",
        "Data and probability",
        "Numëro rastet e favorshme dhe krahasoji me të gjitha rastet.",
        "Count favourable outcomes and compare them with all outcomes.",
    ),
    (
        "eng_reading",
        "english",
        "Lexim dhe fjalor",
        "Reading and vocabulary",
        "Use the surrounding words to infer the meaning.",
        "Use the surrounding words to infer the meaning.",
    ),
    (
        "eng_grammar",
        "english",
        "Gramatikë",
        "Grammar",
        "Look for the time marker and match the verb form.",
        "Look for the time marker and match the verb form.",
    ),
    (
        "eng_communication",
        "english",
        "Komunikim",
        "Communication",
        "Choose the response that fits both the situation and tone.",
        "Choose the response that fits both the situation and tone.",
    ),
    (
        "hist_kosovo",
        "history",
        "Historia e Kosovës",
        "History of Kosovo",
        "Vendose ngjarjen në periudhën e duhur historike.",
        "Place the event in the correct historical period.",
    ),
    (
        "hist_europe",
        "history",
        "Historia evropiane",
        "European history",
        "Lidhe ngjarjen me shkakun ose pasojën e saj kryesore.",
        "Connect the event with its main cause or consequence.",
    ),
    (
        "hist_sources",
        "history",
        "Burimet historike",
        "Historical sources",
        "Dallo dëshminë e kohës nga interpretimi i mëvonshëm.",
        "Distinguish contemporary evidence from later interpretation.",
    ),
    (
        "bio_cell",
        "biology",
        "Qeliza",
        "Cell biology",
        "Lidhe organelën me funksionin e saj.",
        "Match the organelle with its function.",
    ),
    (
        "bio_genetics",
        "biology",
        "Gjenetikë",
        "Genetics",
        "Përcakto alelet e prindërve para se të llogaritësh pasardhësit.",
        "Identify the parents' alleles before calculating offspring.",
    ),
    (
        "bio_ecology",
        "biology",
        "Ekologji",
        "Ecology",
        "Ndiq rrjedhën e energjisë dhe marrëdhëniet në ekosistem.",
        "Trace energy flow and relationships in the ecosystem.",
    ),
    (
        "info_algorithms",
        "informatics",
        "Algoritme",
        "Algorithms",
        "Ekzekuto hapat me radhë dhe shëno vlerën pas secilit hap.",
        "Execute the steps in order and track the value after each step.",
    ),
    (
        "info_data",
        "informatics",
        "Të dhëna",
        "Data representation",
        "Kujto bazën e sistemit numerik që po përdoret.",
        "Recall the base of the number system being used.",
    ),
    (
        "info_systems",
        "informatics",
        "Sisteme digjitale",
        "Digital systems",
        "Mendo për funksionin kryesor të komponentit ose protokollit.",
        "Think about the main function of the component or protocol.",
    ),
]

# skill, Albanian prompt, English prompt, Albanian options, English options, correct index, Albanian explanation, English explanation
QUESTIONS = [
    (
        "alb_reading",
        "Fjalia ‘Pas shiut, rrugët shkëlqenin nën dritat e qytetit’ sugjeron se:",
        "The sentence ‘After the rain, the streets shone under the city lights’ suggests that:",
        ["Ishte mesditë", "Rrugët ishin të lagura", "Qyteti ishte pa drita", "Nuk kishte rënë shi"],
        ["It was noon", "The streets were wet", "The city had no lights", "It had not rained"],
        1,
        "Shkëlqimi pas shiut tregon se sipërfaqja e rrugës ishte e lagur.",
        "The shine after rain indicates that the road surface was wet.",
    ),
    (
        "alb_reading",
        "Cila është ideja kryesore e fjalisë: ‘Leximi i përditshëm pasuron fjalorin dhe forcon përqendrimin’?",
        "What is the main idea of: ‘Daily reading enriches vocabulary and strengthens concentration’?",
        [
            "Leximi sjell dy përfitime",
            "Fjalori nuk ndryshon",
            "Përqendrimi pengon leximin",
            "Duhet lexuar vetëm në shkollë",
        ],
        [
            "Reading has two benefits",
            "Vocabulary never changes",
            "Concentration prevents reading",
            "Reading belongs only at school",
        ],
        0,
        "Fjalia paraqet dy përfitime të leximit të përditshëm.",
        "The sentence states two benefits of daily reading.",
    ),
    (
        "alb_reading",
        "Në shprehjen ‘Ora vraponte, por puna mbetej’, fjala ‘vraponte’ nënkupton se:",
        "In ‘The clock raced, but the work remained’, ‘raced’ means that:",
        ["Ora ishte prishur", "Koha kalonte shpejt", "Dikush po vraponte", "Puna ishte përfunduar"],
        [
            "The clock was broken",
            "Time passed quickly",
            "Someone was running",
            "The work was finished",
        ],
        1,
        "Folja përdoret figurativisht për kalimin e shpejtë të kohës.",
        "The verb is used figuratively for time passing quickly.",
    ),
    (
        "alb_grammar",
        "Cila fjalë është mbiemër në fjalinë ‘Nxënësi i kujdesshëm kontrolloi përgjigjen’?",
        "Which word is an adjective in ‘The careful student checked the answer’?",
        ["Nxënësi", "i kujdesshëm", "kontrolloi", "përgjigjen"],
        ["student", "careful", "checked", "answer"],
        1,
        "‘I kujdesshëm’ përshkruan emrin ‘nxënësi’, prandaj është mbiemër.",
        "‘Careful’ describes the noun ‘student’, so it is an adjective.",
    ),
    (
        "alb_grammar",
        "Cila fjali përdor drejt presjen?",
        "Which sentence uses the comma correctly?",
        [
            "Arta bleu libra fletore, dhe lapsa.",
            "Arta, bleu libra fletore dhe lapsa.",
            "Arta bleu libra, fletore dhe lapsa.",
            "Arta bleu, libra, fletore dhe lapsa.",
        ],
        [
            "Arta bought books notebooks, and pencils.",
            "Arta, bought books notebooks and pencils.",
            "Arta bought books, notebooks and pencils.",
            "Arta bought, books, notebooks and pencils.",
        ],
        2,
        "Presja ndan elementet e një numërimi.",
        "The comma separates items in a list.",
    ),
    (
        "alb_grammar",
        "Në fjalinë ‘Ata do të udhëtojnë nesër’, folja është në:",
        "In ‘They will travel tomorrow’, the verb is in the:",
        ["Të shkuarën", "Të tashmen", "Të ardhmen", "Urdhëroren"],
        ["Past", "Present", "Future", "Imperative"],
        2,
        "Ndërtimi ‘do të udhëtojnë’ shpreh kohën e ardhme.",
        "‘Will travel’ expresses the future tense.",
    ),
    (
        "alb_literature",
        "Krahasimi zakonisht dallohet nga përdorimi i fjalës:",
        "A simile is commonly signalled by the word:",
        ["sepse", "sikur", "por", "prandaj"],
        ["because", "like", "but", "therefore"],
        1,
        "‘Sikur’ lidh dy elemente në një krahasim të shprehur.",
        "‘Like’ explicitly connects two elements in a comparison.",
    ),
    (
        "alb_literature",
        "Personifikimi i jep një sendi ose dukurie:",
        "Personification gives an object or phenomenon:",
        ["Veti njerëzore", "Një datë historike", "Një formulë", "Vetëm rimë"],
        ["Human qualities", "A historical date", "A formula", "Only rhyme"],
        0,
        "Personifikimi ua jep tiparet njerëzore gjërave jo njerëzore.",
        "Personification gives human qualities to non-human things.",
    ),
    (
        "alb_literature",
        "Narratori në vetën e parë përdor zakonisht përemrin:",
        "A first-person narrator usually uses the pronoun:",
        ["Ai", "Ata", "Unë", "Ju"],
        ["He", "They", "I", "You"],
        2,
        "Rrëfimi në vetën e parë paraqitet nga këndvështrimi ‘unë’.",
        "First-person narration uses the ‘I’ point of view.",
    ),
    (
        "math_algebra",
        "Zgjidh ekuacionin 3x + 6 = 18.",
        "Solve 3x + 6 = 18.",
        ["2", "3", "4", "6"],
        ["2", "3", "4", "6"],
        2,
        "Zbrit 6: 3x=12. Pjesëto me 3: x=4.",
        "Subtract 6: 3x=12. Divide by 3: x=4.",
    ),
    (
        "math_algebra",
        "Nëse 2(x − 1) = 10, sa është x?",
        "If 2(x − 1) = 10, what is x?",
        ["4", "5", "6", "7"],
        ["4", "5", "6", "7"],
        2,
        "Pjesëto me 2: x−1=5, pastaj shto 1: x=6.",
        "Divide by 2: x−1=5, then add 1: x=6.",
    ),
    (
        "math_algebra",
        "Faktorizo x² − 9.",
        "Factor x² − 9.",
        ["(x−3)(x+3)", "(x−9)(x+1)", "(x−3)²", "x(x−9)"],
        ["(x−3)(x+3)", "(x−9)(x+1)", "(x−3)²", "x(x−9)"],
        0,
        "Është diferencë katrorësh: a²−b²=(a−b)(a+b).",
        "It is a difference of squares: a²−b²=(a−b)(a+b).",
    ),
    (
        "math_geometry",
        "Sa është sipërfaqja e një drejtkëndëshi me brinjë 5 cm dhe 8 cm?",
        "What is the area of a rectangle with sides 5 cm and 8 cm?",
        ["13 cm²", "26 cm²", "40 cm²", "80 cm²"],
        ["13 cm²", "26 cm²", "40 cm²", "80 cm²"],
        2,
        "Sipërfaqja është gjatësia herë gjerësia: 5×8=40 cm².",
        "Area is length times width: 5×8=40 cm².",
    ),
    (
        "math_geometry",
        "Një trekëndësh kënddrejtë ka katete 3 dhe 4. Sa është hipotenuza?",
        "A right triangle has legs 3 and 4. What is the hypotenuse?",
        ["5", "6", "7", "8"],
        ["5", "6", "7", "8"],
        0,
        "Sipas Pitagorës: √(3²+4²)=√25=5.",
        "By Pythagoras: √(3²+4²)=√25=5.",
    ),
    (
        "math_geometry",
        "Sa gradë është shuma e këndeve të brendshme të një trekëndëshi?",
        "What is the sum of a triangle's interior angles?",
        ["90°", "180°", "270°", "360°"],
        ["90°", "180°", "270°", "360°"],
        1,
        "Këndet e brendshme të çdo trekëndëshi kanë shumë 180°.",
        "The interior angles of every triangle sum to 180°.",
    ),
    (
        "math_data",
        "Një monedhë hidhet një herë. Probabiliteti për stemë është:",
        "A fair coin is tossed once. The probability of heads is:",
        ["0", "1/4", "1/2", "1"],
        ["0", "1/4", "1/2", "1"],
        2,
        "Ka një rezultat të favorshëm nga dy rezultate të barabarta: 1/2.",
        "There is one favourable outcome among two equally likely outcomes: 1/2.",
    ),
    (
        "math_data",
        "Gjej mesataren e numrave 4, 6 dhe 8.",
        "Find the mean of 4, 6 and 8.",
        ["5", "6", "7", "18"],
        ["5", "6", "7", "18"],
        1,
        "(4+6+8)/3 = 18/3 = 6.",
        "(4+6+8)/3 = 18/3 = 6.",
    ),
    (
        "math_data",
        "Në një kuti ka 3 topa të kuq dhe 2 të kaltër. Probabiliteti për të kuq është:",
        "A box has 3 red and 2 blue balls. The probability of red is:",
        ["2/5", "3/5", "1/2", "3/2"],
        ["2/5", "3/5", "1/2", "3/2"],
        1,
        "Janë 3 raste të favorshme nga 5 topa gjithsej: 3/5.",
        "There are 3 favourable outcomes among 5 balls: 3/5.",
    ),
    (
        "eng_reading",
        "In ‘The task was challenging, yet Mira persisted’, persisted means:",
        "In ‘The task was challenging, yet Mira persisted’, persisted means:",
        ["u dorëzua", "vazhdoi", "harroi", "u ankua"],
        ["gave up", "continued", "forgot", "complained"],
        1,
        "‘Persisted’ means continued despite difficulty.",
        "‘Persisted’ means continued despite difficulty.",
    ),
    (
        "eng_reading",
        "Choose the closest meaning of ‘brief’ in ‘a brief meeting’.",
        "Choose the closest meaning of ‘brief’ in ‘a brief meeting’.",
        ["i zhurmshëm", "i shkurtër", "i fshehtë", "i vonshëm"],
        ["noisy", "short", "secret", "late"],
        1,
        "In this context, ‘brief’ means short in duration.",
        "In this context, ‘brief’ means short in duration.",
    ),
    (
        "eng_reading",
        "The sign ‘Library closes at 18:00’ tells readers:",
        "The sign ‘Library closes at 18:00’ tells readers:",
        ["kur hapet", "ku ndodhet", "kur mbyllet", "sa kushton"],
        ["when it opens", "where it is", "when it closes", "how much it costs"],
        2,
        "The sign gives the library's closing time.",
        "The sign gives the library's closing time.",
    ),
    (
        "eng_grammar",
        "She ___ to school every day.",
        "She ___ to school every day.",
        ["go", "goes", "went", "going"],
        ["go", "goes", "went", "going"],
        1,
        "The third-person singular present form is ‘goes’.",
        "The third-person singular present form is ‘goes’.",
    ),
    (
        "eng_grammar",
        "They ___ the test yesterday.",
        "They ___ the test yesterday.",
        ["finish", "finishes", "finished", "will finish"],
        ["finish", "finishes", "finished", "will finish"],
        2,
        "‘Yesterday’ requires the past form ‘finished’.",
        "‘Yesterday’ requires the past form ‘finished’.",
    ),
    (
        "eng_grammar",
        "If it rains, we ___ at home.",
        "If it rains, we ___ at home.",
        ["stay", "stayed", "will stay", "staying"],
        ["stay", "stayed", "will stay", "staying"],
        2,
        "The first conditional uses present after ‘if’ and ‘will’ in the result.",
        "The first conditional uses present after ‘if’ and ‘will’ in the result.",
    ),
    (
        "eng_communication",
        "What is the most polite way to ask for help?",
        "What is the most polite way to ask for help?",
        ["Help me now.", "Could you please help me?", "You must help.", "Why are you not helping?"],
        ["Help me now.", "Could you please help me?", "You must help.", "Why are you not helping?"],
        1,
        "‘Could you please’ makes the request polite.",
        "‘Could you please’ makes the request polite.",
    ),
    (
        "eng_communication",
        "A friend says, ‘I passed the exam!’ The best response is:",
        "A friend says, ‘I passed the exam!’ The best response is:",
        ["Congratulations!", "Never mind.", "I disagree.", "Be quiet."],
        ["Congratulations!", "Never mind.", "I disagree.", "Be quiet."],
        0,
        "‘Congratulations!’ appropriately responds to good news.",
        "‘Congratulations!’ appropriately responds to good news.",
    ),
    (
        "eng_communication",
        "You did not hear a question. What should you say?",
        "You did not hear a question. What should you say?",
        ["Repeat.", "Could you repeat that, please?", "That is wrong.", "I do not care."],
        ["Repeat.", "Could you repeat that, please?", "That is wrong.", "I do not care."],
        1,
        "The polite request clearly asks the speaker to repeat.",
        "The polite request clearly asks the speaker to repeat.",
    ),
    (
        "hist_kosovo",
        "Lidhja Shqiptare e Prizrenit u themelua në vitin:",
        "The Albanian League of Prizren was founded in:",
        ["1389", "1878", "1912", "1999"],
        ["1389", "1878", "1912", "1999"],
        1,
        "Lidhja Shqiptare e Prizrenit u themelua më 1878.",
        "The Albanian League of Prizren was founded in 1878.",
    ),
    (
        "hist_kosovo",
        "Pavarësia e Kosovës u shpall më:",
        "Kosovo declared independence on:",
        ["17 shkurt 2008", "28 nëntor 1912", "12 qershor 1999", "9 maj 1950"],
        ["17 February 2008", "28 November 1912", "12 June 1999", "9 May 1950"],
        0,
        "Kuvendi i Kosovës shpalli pavarësinë më 17 shkurt 2008.",
        "The Assembly of Kosovo declared independence on 17 February 2008.",
    ),
    (
        "hist_kosovo",
        "Cila ngjarje ndodhi më herët?",
        "Which event happened earlier?",
        [
            "Shpallja e pavarësisë së Kosovës",
            "Themelimi i Lidhjes së Prizrenit",
            "Përfundimi i Luftës së Dytë Botërore",
            "Fillimi i shekullit XXI",
        ],
        [
            "Kosovo's declaration of independence",
            "Founding of the League of Prizren",
            "End of World War II",
            "Start of the 21st century",
        ],
        1,
        "Viti 1878 vjen para viteve 1945, 2001 dhe 2008.",
        "The year 1878 precedes 1945, 2001 and 2008.",
    ),
    (
        "hist_europe",
        "Revolucioni Industrial filloi së pari në:",
        "The Industrial Revolution began first in:",
        ["Britani të Madhe", "Itali", "Greqi", "Norvegji"],
        ["Great Britain", "Italy", "Greece", "Norway"],
        0,
        "Britania e Madhe ishte vendi i parë i industrializimit të gjerë.",
        "Great Britain was the first country to industrialise widely.",
    ),
    (
        "hist_europe",
        "Cila ngjarje nisi në vitin 1789?",
        "Which event began in 1789?",
        [
            "Revolucioni Francez",
            "Lufta e Parë Botërore",
            "Rënia e Murit të Berlinit",
            "Reformacioni",
        ],
        ["French Revolution", "First World War", "Fall of the Berlin Wall", "Reformation"],
        0,
        "Revolucioni Francez filloi në vitin 1789.",
        "The French Revolution began in 1789.",
    ),
    (
        "hist_europe",
        "Lufta e Dytë Botërore në Evropë përfundoi në:",
        "The Second World War in Europe ended in:",
        ["1918", "1939", "1945", "1989"],
        ["1918", "1939", "1945", "1989"],
        2,
        "Lufta përfundoi në Evropë në maj 1945.",
        "The war in Europe ended in May 1945.",
    ),
    (
        "hist_sources",
        "Cili është burim historik parësor?",
        "Which is a primary historical source?",
        [
            "Një ditar i shkruar gjatë ngjarjes",
            "Një tekst shkollor modern",
            "Një dokumentar i ri",
            "Një përmbledhje enciklopedike",
        ],
        [
            "A diary written during the event",
            "A modern textbook",
            "A recent documentary",
            "An encyclopaedia summary",
        ],
        0,
        "Ditari i kohës është dëshmi e drejtpërdrejtë e ngjarjes.",
        "A contemporary diary is direct evidence from the event.",
    ),
    (
        "hist_sources",
        "Pse historiani krahason disa burime?",
        "Why does a historian compare several sources?",
        [
            "Për të kontrolluar dëshmitë dhe paragjykimet",
            "Për të shmangur datat",
            "Për të shkruar më gjatë",
            "Për të zgjedhur vetëm burimin më të ri",
        ],
        [
            "To check evidence and bias",
            "To avoid dates",
            "To write more",
            "To select only the newest source",
        ],
        0,
        "Krahasimi ndihmon të verifikohen faktet dhe këndvështrimet.",
        "Comparison helps verify facts and perspectives.",
    ),
    (
        "hist_sources",
        "Një fotografi historike duhet analizuar duke pyetur:",
        "A historical photograph should be analysed by asking:",
        [
            "Kush e krijoi dhe në çfarë konteksti",
            "A është me ngjyra",
            "A është e bukur",
            "Sa kushton korniza",
        ],
        [
            "Who created it and in what context",
            "Whether it is in colour",
            "Whether it is beautiful",
            "How much the frame costs",
        ],
        0,
        "Autori dhe konteksti ndihmojnë të vlerësohet dëshmia.",
        "Authorship and context help evaluate the evidence.",
    ),
    (
        "bio_cell",
        "Cila organele prodhon shumicën e energjisë së qelizës?",
        "Which organelle produces most of a cell's usable energy?",
        ["Bërthama", "Mitokondria", "Ribozomi", "Vakuola"],
        ["Nucleus", "Mitochondrion", "Ribosome", "Vacuole"],
        1,
        "Mitokondria kryen frymëmarrjen qelizore dhe prodhon ATP.",
        "Mitochondria perform cellular respiration and produce ATP.",
    ),
    (
        "bio_cell",
        "Membrana qelizore kontrollon:",
        "The cell membrane controls:",
        ["Kalimin e substancave", "Kodimin e ADN-së", "Prodhimin e dritës", "Formën e planetit"],
        ["Movement of substances", "DNA coding", "Production of light", "The shape of the planet"],
        0,
        "Membrana rregullon çfarë hyn dhe del nga qeliza.",
        "The membrane regulates what enters and leaves the cell.",
    ),
    (
        "bio_cell",
        "Ribozomet janë vendi ku prodhohen:",
        "Ribosomes are the site where cells make:",
        ["Proteinat", "Kromozomet", "Lipidet e tokës", "Mineralet"],
        ["Proteins", "Chromosomes", "Soil lipids", "Minerals"],
        0,
        "Ribozomet përkthejnë informacionin gjenetik në proteina.",
        "Ribosomes translate genetic information into proteins.",
    ),
    (
        "bio_genetics",
        "Njësia bazë e trashëgimisë është:",
        "The basic unit of heredity is the:",
        ["Gjeni", "Organi", "Indi", "Ekosistemi"],
        ["Gene", "Organ", "Tissue", "Ecosystem"],
        0,
        "Gjeni është segment ADN-je që bart informacion trashëgues.",
        "A gene is a DNA segment carrying hereditary information.",
    ),
    (
        "bio_genetics",
        "Nëse A është alel dominant, individi Aa shfaq:",
        "If A is dominant, an Aa individual shows the:",
        ["Tiparin dominant", "Vetëm tiparin recesiv", "Asnjë tipar", "Dy specie"],
        ["Dominant trait", "Only the recessive trait", "No trait", "Two species"],
        0,
        "Një alel dominant mjafton që tipari të shfaqet.",
        "One dominant allele is enough for the trait to appear.",
    ),
    (
        "bio_genetics",
        "ADN-ja gjendet kryesisht në:",
        "DNA is found mainly in the:",
        ["Bërthamë", "Mur qelizor", "Citoplazmë jashtë qelizës", "Gjymtyrë"],
        ["Nucleus", "Cell wall", "Cytoplasm outside the cell", "Limbs"],
        0,
        "Në qelizat eukariote, pjesa më e madhe e ADN-së është në bërthamë.",
        "In eukaryotic cells, most DNA is in the nucleus.",
    ),
    (
        "bio_ecology",
        "Në një zinxhir ushqimor, bimët janë:",
        "In a food chain, plants are:",
        ["Prodhues", "Konsumatorë dytësorë", "Shpërbërës", "Grabitqarë"],
        ["Producers", "Secondary consumers", "Decomposers", "Predators"],
        0,
        "Bimët prodhojnë lëndë organike me fotosintezë.",
        "Plants produce organic matter through photosynthesis.",
    ),
    (
        "bio_ecology",
        "Cila marrëdhënie u sjell dobi të dy organizmave?",
        "Which relationship benefits both organisms?",
        ["Mutualizmi", "Parazitizmi", "Grabitja", "Konkurrenca"],
        ["Mutualism", "Parasitism", "Predation", "Competition"],
        0,
        "Në mutualizëm të dy organizmat përfitojnë.",
        "In mutualism both organisms benefit.",
    ),
    (
        "bio_ecology",
        "Energjia hyn në shumicën e ekosistemeve nga:",
        "Energy enters most ecosystems from:",
        ["Dielli", "Hëna", "Toka e thatë", "Grabitqarët"],
        ["The Sun", "The Moon", "Dry soil", "Predators"],
        0,
        "Fotosinteza kap energjinë e Diellit dhe e fut në zinxhirin ushqimor.",
        "Photosynthesis captures solar energy and introduces it into food chains.",
    ),
    (
        "info_algorithms",
        "Nëse x=2 dhe pastaj x=x+3, sa bëhet x?",
        "If x=2 and then x=x+3, what is x?",
        ["2", "3", "5", "6"],
        ["2", "3", "5", "6"],
        2,
        "Vlera e re është 2+3=5.",
        "The new value is 2+3=5.",
    ),
    (
        "info_algorithms",
        "Cila strukturë përsërit një grup hapash?",
        "Which structure repeats a group of steps?",
        ["Cikli", "Variabla", "Komenti", "Skedari"],
        ["Loop", "Variable", "Comment", "File"],
        0,
        "Cikli ekzekuton të njëjtat hapa disa herë.",
        "A loop executes the same steps repeatedly.",
    ),
    (
        "info_algorithms",
        "Një kusht if ekzekuton kodin kur kushti është:",
        "An if statement executes its block when the condition is:",
        ["I vërtetë", "Gjithmonë i gabuar", "Tekst i gjatë", "Skedar"],
        ["True", "Always false", "Long text", "A file"],
        0,
        "Blloku i if ekzekutohet kur shprehja logjike vlerësohet true.",
        "The if block runs when its logical expression evaluates to true.",
    ),
    (
        "info_data",
        "Numri binar 101 është sa në sistemin dhjetor?",
        "What is binary 101 in decimal?",
        ["3", "4", "5", "6"],
        ["3", "4", "5", "6"],
        2,
        "1×4 + 0×2 + 1×1 = 5.",
        "1×4 + 0×2 + 1×1 = 5.",
    ),
    (
        "info_data",
        "Një bit mund të ketë vlerën:",
        "A bit can have the value:",
        ["Vetëm 0 ose 1", "0 deri 9", "Çdo shkronjë", "Vetëm 8"],
        ["Only 0 or 1", "0 through 9", "Any letter", "Only 8"],
        0,
        "Biti është njësia binare me dy gjendje, 0 dhe 1.",
        "A bit is a binary unit with two states, 0 and 1.",
    ),
    (
        "info_data",
        "Tetë bitë formojnë një:",
        "Eight bits form one:",
        ["Bajt", "Kilobajt", "Piksel", "Algoritëm"],
        ["Byte", "Kilobyte", "Pixel", "Algorithm"],
        0,
        "Një bajt përbëhet nga tetë bitë.",
        "One byte consists of eight bits.",
    ),
    (
        "info_systems",
        "Cili komponent ruan përkohësisht të dhënat që po përdoren?",
        "Which component temporarily stores data currently in use?",
        ["RAM", "Printeri", "Tastiera", "Ruteri"],
        ["RAM", "Printer", "Keyboard", "Router"],
        0,
        "RAM mban përkohësisht programet dhe të dhënat aktive.",
        "RAM temporarily holds active programs and data.",
    ),
    (
        "info_systems",
        "HTTP përdoret kryesisht për:",
        "HTTP is mainly used for:",
        [
            "Shkëmbimin e faqeve në web",
            "Karikimin e baterisë",
            "Shtypjen në letër",
            "Matjen e temperaturës",
        ],
        [
            "Transferring web pages",
            "Charging a battery",
            "Printing on paper",
            "Measuring temperature",
        ],
        0,
        "HTTP është protokoll për komunikimin mes shfletuesit dhe serverit web.",
        "HTTP is a protocol for communication between a browser and a web server.",
    ),
    (
        "info_systems",
        "Cila fjalëkalim është më i fortë?",
        "Which password is strongest?",
        ["123456", "password", "Arta2008", "L7!qP2#vR9"],
        ["123456", "password", "Arta2008", "L7!qP2#vR9"],
        3,
        "Fjalëkalimi i gjatë me lloje të ndryshme karakteresh është më i vështirë për t'u hamendësuar.",
        "A long password with varied character types is harder to guess.",
    ),
]


def seed_demo_content(session) -> int:
    for order, (code, sq, en, is_core) in enumerate(SUBJECTS):
        item = session.get(Subject, code) or Subject(code=code)
        item.name_sq, item.name_en, item.is_core, item.sort_order = sq, en, is_core, order
        session.add(item)
    session.flush()

    skill_hints = {}
    for index, (code, subject, sq, en, hint_sq, hint_en) in enumerate(SKILLS):
        item = session.get(Skill, code) or Skill(code=code)
        item.subject_code, item.name_sq, item.name_en = subject, sq, en
        item.sort_order = index % 3
        skill_hints[code] = (hint_sq, hint_en)
        session.add(item)
    session.flush()

    counts: dict[str, int] = {}
    for row in QUESTIONS:
        (
            skill,
            prompt_sq,
            prompt_en,
            options_sq,
            options_en,
            correct,
            explanation_sq,
            explanation_en,
        ) = row
        position = counts.get(skill, 0)
        counts[skill] = position + 1
        question_id = uuid.uuid5(NAMESPACE, f"{skill}:{position}")
        item = session.get(Question, question_id) or Question(id=question_id)
        item.skill_code = skill
        item.prompt_sq, item.prompt_en = prompt_sq, prompt_en
        item.options_sq, item.options_en = options_sq, options_en
        item.correct_index = correct
        item.hint_sq, item.hint_en = skill_hints[skill]
        item.explanation_sq, item.explanation_en = explanation_sq, explanation_en
        item.difficulty = position + 1
        item.source_label = "Matura AI demo bank v1"
        item.diagnostic_order = 1 if position == 0 else None
        item.is_active = True
        session.add(item)
    session.commit()
    return len(QUESTIONS)
